

compile:
	cd src/ ; make compile

run:	
	java -jar foafpath.jar


# this gets co-depiction data from remote service
# (which isn't always available...)

fetch:
	./getrawinfo.pl > linkdata.dat

summary:

	./getrawinfo.pl > rawinfotable.html
