
var field_friend='Friend';
var field_title='Title (Mr, Mrs, Dr, etc)';
var field_firstName='First Name';
var field_surname='Last Name (Family/Given)';
var field_nick='Nickname';
var field_email='Your Email Address';
var field_homepage='Homepage';
var field_depiction='Your Picture';
var field_phone='Phone Number';
var field_workplaceHomepage='Work Homepage';
var field_workInfoHomepage='Page describing what you do at work';
var field_schoolHomepage='School Homepage';
var field_spamProtect='Protect email addresses from spammers';
var field_friendEmail='Email';
var field_friendName='Name';
var field_friendSeeAlso='See Also';
var msg_missingRequired='You must complete these fields:';
var msg_missingFriendEmail='An Email Address For ?';