
var field_friend='Ami';
var field_title='Salutation (M., Mme, Dr, etc)';
var field_firstName='Prénom';
var field_surname='Nom';
var field_nick='Surnom ou pseudo';
var field_email='Votre adresse de courrier';
var field_homepage='Page web';
var field_depiction='Votre photo';
var field_phone='Téléphone';
var field_workplaceHomepage='Page web au travail';
var field_workInfoHomepage='Page décrivant votre travail';
var field_schoolHomepage='Page web de votre école';
var field_spamProtect='Adresse de courrier protégé des spammeurs';
var field_friendEmail='Adresse de courrier';
var field_friendName='Non';
var field_friendSeeAlso='Voir aussi';
var msg_missingRequired='Vous devez compléter ces champs:';
var msg_missingFriendEmail='Une adresse de courrier pour ?';