#!/usr/bin/env ruby
# RDF query (in memory version), Dan Brickley <danbri@w3.org>

require 'squish'
require 'basicrdf'

#vdl = Loader.rdf2graph 'rdf_vdl.xml', 'http://www.w3.org/2000/01/rdf-schema#'
#`rdfdump -o ntriples file:rdf_vdl.xml > rdf_vdl.nt`

def shortname (uri)
  uri = uri.to_s
  uri.gsub!('http://www.w3.org/1999/02/22-rdf-syntax-ns#', 'rdf:')
  uri.gsub!(/http:\/\/www.w3.org\/2000\/01\/rdf-schema#/, 'rdfs:')
  return uri
end

vdl = Loader.nt2graph # read from stdin

FOAF = vdl.reg_xmlns 'http://xmlns.com/foaf/0.1/', 'foaf'
DC = vdl.reg_xmlns 'http://purl.org/dc/elements/1.1/', 'dc'
RDF = vdl.reg_xmlns 'http://www.w3.org/1999/02/22-rdf-syntax-ns#','rdf'
VDL = vdl.reg_xmlns 'http://www.w3.org/2000/01/rdf-schema#','vdl'


s1=Statement.new (nil, RDF+'type', VDL+'Class')
s2=Statement.new (nil, RDF+'type', RDF+'Property')
classes = vdl.ask s1
props = vdl.ask s2

puts "// this is an autogenerated Java document created from the RDF at http://xmlns.com/foaf/0.1/"

puts "import hp....java;"
puts "public class FOAFJena { \n"

classes.subjects.each do |classuri|
  c = Node.getResource classuri, vdl
  # puts "C is #{c.inspect} \n"

  name = shortname(classuri)		#+" label="+c.vdl_label.to_s 

  puts "public static Class {name} ;\n"
  puts "// ...blah blah comment: {c.vdl_comment}; \n"  
end

# todo: are there any multi-valued domain or range declarations?

props.subjects.each do |propuri|
  p = Node.getResource propuri, vdl
  r = p.vdl_range
  rt = r.to_s
  if (r.to_s == "") 
    rt = 'n/a'
  end
  d= p.vdl_domain
  dt = d.to_s
  if (d.to_s == "")
    dt = 'n/a'
  end
  rt = shortname rt
  dt = shortname dt

  name = shortname (propuri) # + " label="+p.vdl_label.to_s
  puts "// property: #{name} \n"
  puts "// property info: #{p.vdl_comment.to_s}</td><td>#{dt}</td><td>#{rt} \n"  
end

puts "\n</table>\n\n"

